<a href="https://colab.research.google.com/github/Luiscal28/adivinanza/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

edades = [18 ,17, 16, 15, 22, 18,]
edades_array = np.array(edades)
#print(edades)
#print(edades_array)
#print(edades_array.dtype)
#print(edades_array.shape)

# birth_year=[]
# for edad in edades:
#   birth_year.append(2024-edad)
#   print(birth_year)

birth_year_array = 2024 - edades_array
print(birth_year_array)

[2006 2007 2008 2009]


In [13]:
n = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print(n)
print(n.shape)
print(n[1][0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
4


In [15]:
edades = [18 ,17, 16, 15, 22, 18, 19]
edades_array = np.array(edades)
mayores_de_edad = edades_array >= 18
print(mayores_de_edad)

[ True False False False  True  True  True]


In [25]:
import numpy as np
recipes = np.genfromtxt("/content/recipes.csv", delimiter=",")
# print(recipes)
# print(recipes.dtype)
# print(recipes.shape)
eggs = recipes[:, 2]
print(eggs[eggs==1])

cupcakes = 2 * recipes[0,:]
coockies = recipes [2,:]

grocery_list = cupcakes + coockies
print(grocery_list)

[1. 1.]
[6.75 3.   5.   2.   2.  ]


In [26]:
a= np. zeros (10)
print (a)
b = np. ones (10)
print (b)
c = np. empty (10)
print (c)
print (b + c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
